// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gudkehzonntowrmxshnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1ZGtlaHpvbm50b3dybXhzaG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NDQ1ODksImV4cCI6MjA1OTEyMDU4OX0.9zDt4q3_UDHnz8_Gs92De8QIRhEiFvH8tTJteKlsxoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);